"""
Generate a freeze artifact: what was declared to be running, and from when.

WHY THIS EXISTS
---------------
A freeze asserts "this exact configuration was running from this date." The
value is entirely in the commit timestamp, which cannot be backdated
convincingly, so the artifact must be exactly right at the moment it is
committed. That rules out hand-transcription: StockBot's config.py carries at
least four comments that disagree with their own values (RISK_PER_TRADE_PCT is
0.05 while the comment says 2.5%), and a human copying that file would record
the comment.

HOW IT READS THE CONFIG
-----------------------
It parses config.py with `ast` at the DEPLOYED commit -- not the working tree,
and never by importing it. Two reasons. Importing executes module-level code,
which raises without Alpaca credentials present. And parsing records only
literal constants: the credentials are `os.getenv(...)` CALLS, so they are
excluded by the shape of the expression rather than by a filter that could be
forgotten.

Run: python freeze/freeze.py --name <name>
"""

from __future__ import annotations

import argparse
import ast
import json
import re
import subprocess
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
STOCKBOT = Path.home() / "Desktop" / "StockBot"
DEPLOYED = ROOT / "deploy" / "DEPLOYED.md"


def deployed_facts() -> dict:
    """Pull the verified deployment record. This file is machine-generated by
    deploy/verify.sh, so it is the authority on what is actually running."""
    text = DEPLOYED.read_text()
    facts = {}
    for line in text.splitlines():
        m = re.match(r"\|\s*([^|]+?)\s*\|\s*(.+?)\s*\|\s*$", line)
        if m and m.group(1) not in ("", "---"):
            facts[m.group(1)] = m.group(2).strip("`")
    return facts


def config_literals(commit: str) -> dict:
    """Module-level literal assignments in StockBot's config.py at `commit`.

    Anything that is not a literal -- os.getenv calls, f-strings, computed
    expressions -- is skipped, which is how credentials stay out."""
    src = subprocess.run(
        ["git", "-C", str(STOCKBOT), "show", f"{commit}:config.py"],
        capture_output=True, text=True, check=True,
    ).stdout
    out = {}
    for node in ast.parse(src).body:
        if not isinstance(node, ast.Assign) or len(node.targets) != 1:
            continue
        target = node.targets[0]
        if not isinstance(target, ast.Name) or not target.id.isupper():
            continue
        try:
            out[target.id] = ast.literal_eval(node.value)
        except (ValueError, TypeError, SyntaxError):
            continue  # not a literal: a getenv call, an f-string, a computation
    return out


def account_id() -> tuple[str, str]:
    """The broker account this freeze applies to, and where the value came from.

    deploy/verify.sh reports only PAPER vs LIVE -- it does not capture the
    account number -- so this is read from the boundary table in
    results/live/README.md. That is a maintained document, not a machine
    reading, and the freeze says so rather than implying verification it does
    not have."""
    src = ROOT / "results" / "live" / "README.md"
    for line in src.read_text().splitlines():
        if line.strip().startswith("| account"):
            ids = re.findall(r"`(PA[A-Z0-9]{6,})`", line)
            if ids:
                return ids[-1], f"{src.relative_to(ROOT)} boundary table (not machine-verified)"
    return "", "not found"


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--name", required=True, help="freeze name, e.g. stockbot-momentum-1")
    ap.add_argument("--note", default="", help="one line on why this freeze exists")
    args = ap.parse_args()

    facts = deployed_facts()
    commit = facts["StockBot commit"]
    cfg = config_literals(commit)
    acct_id, acct_src = account_id()

    watchlist = cfg.pop("WATCHLIST", [])
    doc = {
        "name": args.name,
        "effective_utc": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "note": args.note,
        "system": {
            "bot": "StockBot",
            "strategy": "stockbot_momentum",
            "commit": commit,
            "commit_subject": facts.get("subject", ""),
            "verified_utc": facts.get("verified (UTC)", ""),
        },
        "account": {
            "id": acct_id,
            "id_source": acct_src,
            "type": facts.get("broker account", ""),
            "equity_at_freeze": facts.get("equity at verify", ""),
            "open_positions_at_freeze": facts.get("open positions", ""),
        },
        "universe": {"n_symbols": len(watchlist), "symbols": sorted(watchlist)},
        "config": {k: cfg[k] for k in sorted(cfg)},
    }

    out = ROOT / "freeze" / f"{args.name}.json"
    out.write_text(json.dumps(doc, indent=2, sort_keys=False) + "\n")
    print(f"wrote {out.relative_to(ROOT)}")
    print(f"  commit   {commit[:12]}")
    print(f"  symbols  {len(watchlist)}")
    print(f"  settings {len(doc['config'])}")


if __name__ == "__main__":
    main()
